  },
                                    {
                                        "name": "float_24",
                                        "distribution": "CONTINUOUS",
                                        "type": "float",
                                        "status": "normal"
                                    },
                                    {
                                        "name": "x5",
                                        "distribution": "CONTINUOUS",
                                        "type": "float",
                                        "status": "normal"
                                    },
                                    {
                                        "name": "x6",
                                        "distribution": "CONTINUOUS",
                                        "type": "float",
                                        "status": "normal"
                                    },
                                    {
                                        "name": "x7",
                                        "distribution": "CONTINUOUS",
                                        "type": "float",
                                        "status": "normal"
                                    },
                                    {
                                        "name": "float_28",
                                        "distribution": "CONTINUOUS",
                                        "type": "float",
                                        "status": "normal"
                                    },
                                    {
                                        "name": "float_29",
                                        "distribution": "CONTINUOUS",
                                        "type": "float",
                                        "status": "normal"
                                    },
                                    {
                                        "name": "float_30",
                                        "distribution": "CONTINUOUS",
                                        "type": "float",
                                        "status": "normal"
                                    },
                                    {
                                        "columnType": "matchColumn",
                                        "name": "unique_index_unique",
                                        "distribution": "CONTINUOUS",
                                        "type": "varchar",
                                        "status": "normal"
                                    }
                                ],
                                "outputCategory": [
                                    "数据集|融合集"
                                ],
                                "datasetTag": false,
                                "traceColumn": {},
                                "datasetType": "X",
                                "matchColumn": {
                                    "final": "unique_index_unique",
                                    "1656552498002919424": "varcharId"
                                }
                            },
                            "extra": "{\"result_file_ori\":\"dev-sf2-lts-n1/permanent/nid_1656551243780194304/pid_1656565751110172672/fid_1676489357768925185/jid_1676490320432996353/tid_1676491010127568898/dataset/psi_output/dataset/_meta.json\",\"support_download\":\"true\",\"result_id_pre\":\"dev-sf2-lts-n1/permanent/nid_1656551243780194304/pid_1656565751110172672/fid_1676489357768925185/jid_1676490320432996353/tid_1676491010127568898/dataset/psi_output/dataset/_meta.json\"}",
                            "count": 2997,
                            "name": "DX_X_feature_3000_0425_281.csv",
                            "description": "",
                            "contentType": "parquet",
                            "remoteId": "dev-sf2-lts-n1/permanent/nid_1656551243780194304/pid_1656565751110172672/fid_1676489357768925185/jid_1676490320432996353/tid_1676491313195393025/dataset/output_missing1/dataset.parquet"
                        }
                    }
                ]
            },
            "paramType": "DATASET",
            "paramName": "input1",
            "paramNameCN": ""
        }
    ],
    "settings": {
        "trainingSetPercent": 80,
        "testSetPercent": 20,
        "jobNum": 6,
        "seed": 0,
        "dataSplitName": "<h4 style='margin-bottom:0'>数据集拆分</h4>",
        "paillierNLength": 1024,
        "eps": 1e-05,
        "precisionBit": 64,
        "algorithmSplitName": "<h4 style='margin-bottom:0'>算法配置</h4>",
        "splitMethod": "FIXED",
        "learningRate": 0.1,
        "lrdRate": 0.99,
        "histogram": 100,
        "protocol": "NPZ",
        "lambda": 0.01,
        "optimizer": "BGD",
        "beta1": 0.9,
        "beta2": 0.999,
        "maxIteration": 5,
        "alpha": 0.9,
        "regularMethod": "L2",
        "batchSize": 1000,
        "lossFreq": 0,
        "mpcConfigName": "<h4 style='margin-bottom:0'>MPC配置</h4>"
    },
    "jobId": "1676499580252463106",
    "flowId": "1676489357768925185",
    "containerId": "cn.fudata.LR_NPZ_v2.1.0_01b178f4",
    "wareId": "cn.fudata.LR_NPZ",
    "wareVersion": "v2.1.0",
    "wareType": null,
    "wareServerType": "training",
    "outputDirectory": {
        "temporaryDirectory": "dev-sf2-lts-n2/temporary/nid_1656552239449243648/pid_1656565751110172672/fid_1676489357768925185/jid_1676490320432996353/tid_1676499580252463106/",
        "permanentDirectory": "dev-sf2-lts-n2/permanent/nid_1656552239449243648/pid_1656565751110172672/fid_1676489357768925185/jid_1676490320432996353/tid_1676499580252463106/"
    },
    "isArbiter": 0,
    "extra": {}
}
2023-07-05 15:53:42,898 - [MpcPoolWorker-2:2:870] lr_npz_hybrid_base.py [Line:920] - DEBUG - >>>> LR_NPZ_HYBRID NODATA exists=False
2023-07-05 15:53:42,899 - [MpcPoolWorker-2:2:870] fed_mpc_tools.py [Line:129] - INFO - >>>> LR-NPZ 集群请求链接=http://10.84.150.52:8380//avatar/core/v2/system/resource/tfe/get?wareServerType=training&jobId=1676499580252463106
2023-07-05 15:53:42,929 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u53c2\u6570\u89e3\u6790: START jobid=1676499580252463106 ", "time": 1688543622.8857443}, response: {'code': '0', 'message': 'OK','data': None, 'success': True}
2023-07-05 15:53:42,933 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u6846\u67b6\u53c2\u6570\u89e3\u6790", "time": 1688543622.8863199}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:42,969 - [MpcPoolWorker-2:2:870] fed_mpc_tools.py [Line:25] - INFO - >>>> LR-NPZ 复核mpc集群信息=[{'nid': '1656551243780194304', 'tfeServer': '10.86.254.244:10000', 'tfeServerName': 'fc2a25e5-4bcf-4bc1-9a19-e766c58504b8', 'dataServer': '10.86.254.244:40929', 'dataServerName': 'data_fc2a25e5-4bcf-4bc1-9a19-e766c58504b8'}, {'nid': '1656552498002919424', 'tfeServer': '10.86.143.51:10000', 'tfeServerName': 'c72116c3-a8d3-4e1d-bf55-28f69c9d5d7f', 'dataServer': '10.86.143.51:40929', 'dataServerName': 'data_c72116c3-a8d3-4e1d-bf55-28f69c9d5d7f'}, {'nid': '1656552239449243648', 'tfeServer': '10.86.29.50:10000', 'tfeServerName': '88da3a9e-f30e-42f8-a2b8-d3c932a7d6a2', 'dataServer': '10.86.29.50:40929', 'dataServerName': 'data_88da3a9e-f30e-42f8-a2b8-d3c932a7d6a2'}], job_id=1676499580252463106
2023-07-05 15:53:42,971 - [MpcPoolWorker-2:2:870] lr_npz_hybrid_base.py [Line:218] - INFO - >>>> LR-NPZ 模型训练数据列名=[{
    "name": "SexNum",
    "distribution": "CONTINUOUS",
    "type": "int",
    "status": "normal",
    "columnType": null
}, {
    "name": "NumChar",
    "distribution": "CONTINUOUS",
    "type": "int",
    "status": "normal",
    "columnType": null
}, {
    "name": "RandomNum100",
    "distribution": "CONTINUOUS",
    "type": "int",
    "status": "normal",
    "columnType": null
}, {
    "name": "TINYINT",
    "distribution": "CONTINUOUS",
    "type": "int",
    "status": "normal",
    "columnType": null
}, {
    "name": "x9",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x10",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x11",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x12",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x13",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x14",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x15",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x16",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x17",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x18",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x19",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x20",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x21",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x22",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x23",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x24",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x25",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x26",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x27",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x28",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x29",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x30",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x31",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x32",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x33",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x34",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x35",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x36",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x37",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "x38",
    "distribution": "CONTINUOUS",
    "type": "float",
    "status": "normal",
    "columnType": null
}, {
    "name": "unique_index_unique",
    "distribution": "CONTINUOUS",
    "type": "varchar",
    "status": "normal",
    "columnType": "matchColumn"
}]
2023-07-05 15:53:42,971 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u4efb\u52a1\u6570\u636e\u53c2\u6570\u89e3\u6790", "time": 1688543622.9698646}
2023-07-05 15:53:42,971 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID setting\u53c2\u6570\u89e3\u6790", "time": 1688543622.969696}
2023-07-05 15:53:42,972 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u53c2\u6570\u89e3\u6790: END", "time": 1688543622.9721344}
2023-07-05 15:53:42,973 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u4efb\u52a1\u914d\u7f6e: START", "time": 1688543622.9726822}
2023-07-05 15:53:42,974 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u5f00\u59cb\u57fa\u4e8e\u540c\u6001\u751f\u6210\u4e09\u5143\u7ec4\u79cd\u5b50", "time": 1688543622.973675}
2023-07-05 15:53:43,010 - [MpcPoolWorker-2:2:870] Commands.py [Line:153] - INFO - FW send event: job=1676499580252463106, target_url=https://10.86.143.51:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=encrypt_x_1656552239449243648, data_block_len=1
2023-07-05 15:53:43,006 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u4efb\u52a1\u6570\u636e\u53c2\u6570\u89e3\u6790", "time": 1688543622.9698646}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:43,011 - [MpcPoolWorker-2:2:870] Commands.py [Line:153] - INFO - FW send event: job=1676499580252463106, target_url=https://10.86.254.244:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=encrypt_x_1656552239449243648, data_block_len=1
2023-07-05 15:53:43,015 - [MpcPoolWorker-2:2:870] EventListener.py [Line:144] - INFO - FW get_event_result: job=1676499580252463106, e_name=encrypt_x_1656551243780194304, role=cn.fudata.LR_NPZ, to=3600s
2023-07-05 15:53:43,015 - [MpcPoolWorker-2:2:870] HttpComms.py [Line:34] - DEBUG - target_url:https://10.86.29.50:10000/gateway/v2/ware/receive, cur_gateway_url:https://10.86.29.50:10000, gateway_url:10.84.61.207:8000, replaced url: http://10.84.61.207:8000/gateway/v2/ware/receive
2023-07-05 15:53:43,017 - [MpcPoolWorker-2:2:870] Commands.py [Line:153] - INFO - FW send event: job=1676499580252463106, target_url=http://10.84.61.207:8000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=encrypt_x_1656552239449243648, data_block_len=1
2023-07-05 15:53:43,020 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID setting\u53c2\u6570\u89e3\u6790", "time": 1688543622.969696}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:43,022 - [MpcPoolWorker-2:2:870] Commands.py [Line:185] - INFO - FW send event success: job=1676499580252463106, target_url=http://10.84.61.207:8000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=encrypt_x_1656552239449243648, data_block_len=1
2023-07-05 15:53:43,028 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u53c2\u6570\u89e3\u6790: END", "time": 1688543622.9721344}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:43,030 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u4efb\u52a1\u914d\u7f6e: START", "time": 1688543622.9726822}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:43,032 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u5f00\u59cb\u57fa\u4e8e\u540c\u6001\u751f\u6210\u4e09\u5143\u7ec4\u79cd\u5b50", "time": 1688543622.973675}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:43,034 - [MpcPoolWorker-2:2:870] Commands.py [Line:185] - INFO - FW send event success: job=1676499580252463106, target_url=https://10.86.254.244:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=encrypt_x_1656552239449243648, data_block_len=1
2023-07-05 15:53:43,071 - [MpcPoolWorker-2:2:870] EventListener.py [Line:99] - INFO - FW get_event_result set[[single]] data local3: jobid=1676499580252463106, e_name=encrypt_x_1656552239449243648/get=encrypt_x_1656551243780194304, ware_id=cn.fudata.LR_NPZ
2023-07-05 15:53:43,597 - [MpcPoolWorker-2:2:870] Commands.py [Line:185] - INFO - FW send event success: job=1676499580252463106, target_url=https://10.86.143.51:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=encrypt_x_1656552239449243648, data_block_len=1
2023-07-05 15:53:43,828 - [MpcPoolWorker-2:2:870] EventListener.py [Line:99] - INFO - FW get_event_result set[[single]] data local3: jobid=1676499580252463106, e_name=encrypt_x_1656552498002919424/get=encrypt_x_1656551243780194304, ware_id=cn.fudata.LR_NPZ
2023-07-05 15:53:43,980 - [MpcPoolWorker-2:2:870] EventListener.py [Line:95] - INFO - FW get_event_result success from queue 2: job=1676499580252463106, e_name=encrypt_x_1656551243780194304, role=cn.fudata.LR_NPZ
2023-07-05 15:53:43,980 - [MpcPoolWorker-2:2:870] WrapUtils.py [Line:15] - DEBUG - get_event_result method execTime: 0.965 s
2023-07-05 15:53:43,980 - [MpcPoolWorker-2:2:870] EventListener.py [Line:144] - INFO - FW get_event_result: job=1676499580252463106, e_name=encrypt_x_1656552498002919424, role=cn.fudata.LR_NPZ, to=3600s
2023-07-05 15:53:43,981 - [MpcPoolWorker-2:2:870] EventListener.py [Line:61] - INFO - FW get_event_result success from local cache 1: job=1676499580252463106, e_name=encrypt_x_1656552498002919424, role=cn.fudata.LR_NPZ, data_len=1
2023-07-05 15:53:43,981 - [MpcPoolWorker-2:2:870] WrapUtils.py [Line:15] - DEBUG - get_event_result method execTime: 0.000 s
2023-07-05 15:53:43,981 - [MpcPoolWorker-2:2:870] EventListener.py [Line:144] - INFO - FW get_event_result: job=1676499580252463106, e_name=encrypt_xy_sub_r_1656551243780194304_1656552239449243648, role=cn.fudata.LR_NPZ, to=3600s
2023-07-05 15:53:43,981 - [MpcPoolWorker-2:2:870] Commands.py [Line:153] - INFO - FW send event: job=1676499580252463106, target_url=https://10.86.143.51:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=encrypt_xy_sub_r_1656552239449243648_1656551243780194304, data_block_len=1
2023-07-05 15:53:43,984 - [MpcPoolWorker-2:2:870] HttpComms.py [Line:34] - DEBUG - target_url:https://10.86.29.50:10000/gateway/v2/ware/receive, cur_gateway_url:https://10.86.29.50:10000, gateway_url:10.84.61.207:8000, replaced url: http://10.84.61.207:8000/gateway/v2/ware/receive
2023-07-05 15:53:43,982 - [MpcPoolWorker-2:2:870] Commands.py [Line:153] - INFO - FW send event: job=1676499580252463106, target_url=https://10.86.254.244:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=encrypt_xy_sub_r_1656552239449243648_1656551243780194304, data_block_len=1
2023-07-05 15:53:43,985 - [MpcPoolWorker-2:2:870] HttpComms.py [Line:34] - DEBUG - target_url:https://10.86.29.50:10000/gateway/v2/ware/receive, cur_gateway_url:https://10.86.29.50:10000, gateway_url:10.84.61.207:8000, replaced url: http://10.84.61.207:8000/gateway/v2/ware/receive
2023-07-05 15:53:43,982 - [MpcPoolWorker-2:2:870] Commands.py [Line:153] - INFO - FW send event: job=1676499580252463106, target_url=https://10.86.143.51:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=encrypt_xy_sub_r_1656552239449243648_1656552498002919424, data_block_len=1
2023-07-05 15:53:43,983 - [MpcPoolWorker-2:2:870] Commands.py [Line:153] - INFO - FW send event: job=1676499580252463106, target_url=https://10.86.254.244:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=encrypt_xy_sub_r_1656552239449243648_1656552498002919424, data_block_len=1
2023-07-05 15:53:43,985 - [MpcPoolWorker-2:2:870] Commands.py [Line:153] - INFO - FW send event: job=1676499580252463106, target_url=http://10.84.61.207:8000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=encrypt_xy_sub_r_1656552239449243648_1656551243780194304, data_block_len=1
2023-07-05 15:53:43,986 - [MpcPoolWorker-2:2:870] Commands.py [Line:153] - INFO - FW send event: job=1676499580252463106, target_url=http://10.84.61.207:8000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=encrypt_xy_sub_r_1656552239449243648_1656552498002919424, data_block_len=1
2023-07-05 15:53:43,990 - [MpcPoolWorker-2:2:870] Commands.py [Line:185] - INFO - FW send event success: job=1676499580252463106, target_url=https://10.86.143.51:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=encrypt_xy_sub_r_1656552239449243648_1656551243780194304, data_block_len=1
2023-07-05 15:53:43,992 - [MpcPoolWorker-2:2:870] Commands.py [Line:185] - INFO - FW send event success: job=1676499580252463106, target_url=http://10.84.61.207:8000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=encrypt_xy_sub_r_1656552239449243648_1656551243780194304, data_block_len=1
2023-07-05 15:53:43,992 - [MpcPoolWorker-2:2:870] Commands.py [Line:185] - INFO - FW send event success: job=1676499580252463106, target_url=http://10.84.61.207:8000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=encrypt_xy_sub_r_1656552239449243648_1656552498002919424, data_block_len=1
2023-07-05 15:53:44,029 - [MpcPoolWorker-2:2:870] Commands.py [Line:185] - INFO - FW send event success: job=1676499580252463106, target_url=https://10.86.254.244:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=encrypt_xy_sub_r_1656552239449243648_1656551243780194304, data_block_len=1
2023-07-05 15:53:44,034 - [MpcPoolWorker-2:2:870] EventListener.py [Line:99] - INFO - FW get_event_result set[[single]] data local3: jobid=1676499580252463106, e_name=encrypt_xy_sub_r_1656552239449243648_1656551243780194304/get=encrypt_xy_sub_r_1656551243780194304_1656552239449243648, ware_id=cn.fudata.LR_NPZ
2023-07-05 15:53:44,035 - [MpcPoolWorker-2:2:870] EventListener.py [Line:99] - INFO - FW get_event_result set[[single]] data local3: jobid=1676499580252463106, e_name=encrypt_xy_sub_r_1656552239449243648_1656552498002919424/get=encrypt_xy_sub_r_1656551243780194304_1656552239449243648, ware_id=cn.fudata.LR_NPZ
2023-07-05 15:53:44,043 - [MpcPoolWorker-2:2:870] Commands.py [Line:185] - INFO - FW send event success: job=1676499580252463106, target_url=https://10.86.143.51:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=encrypt_xy_sub_r_1656552239449243648_1656552498002919424, data_block_len=1
2023-07-05 15:53:44,047 - [MpcPoolWorker-2:2:870] Commands.py [Line:185] - INFO - FW send event success: job=1676499580252463106, target_url=https://10.86.254.244:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=encrypt_xy_sub_r_1656552239449243648_1656552498002919424, data_block_len=1
2023-07-05 15:53:44,128 - [MainProcess:49] EventHandler.py [Line:77] - WARNING - FW web not found job event，from cache: 1676499253109334017
2023-07-05 15:53:44,338 - [MpcPoolWorker-2:2:870] EventListener.py [Line:99] - INFO - FW get_event_result set[[single]] data local3: jobid=1676499580252463106, e_name=encrypt_xy_sub_r_1656552498002919424_1656552239449243648/get=encrypt_xy_sub_r_1656551243780194304_1656552239449243648, ware_id=cn.fudata.LR_NPZ
2023-07-05 15:53:44,425 - [MpcPoolWorker-2:2:870] EventListener.py [Line:99] - INFO - FW get_event_result set[[single]] data local3: jobid=1676499580252463106, e_name=encrypt_xy_sub_r_1656552498002919424_1656551243780194304/get=encrypt_xy_sub_r_1656551243780194304_1656552239449243648, ware_id=cn.fudata.LR_NPZ
2023-07-05 15:53:44,678 - [MpcPoolWorker-2:2:870] EventListener.py [Line:95] - INFO - FW get_event_result success from queue 2: job=1676499580252463106, e_name=encrypt_xy_sub_r_1656551243780194304_1656552239449243648, role=cn.fudata.LR_NPZ
2023-07-05 15:53:44,678 - [MpcPoolWorker-2:2:870] WrapUtils.py [Line:15] - DEBUG - get_event_result method execTime: 0.697 s
2023-07-05 15:53:44,679 - [MpcPoolWorker-2:2:870] EventListener.py [Line:144] - INFO - FW get_event_result: job=1676499580252463106, e_name=encrypt_xy_sub_r_1656552498002919424_1656552239449243648, role=cn.fudata.LR_NPZ, to=3600s
2023-07-05 15:53:44,679 - [MpcPoolWorker-2:2:870] EventListener.py [Line:61] - INFO - FW get_event_result success from local cache 1: job=1676499580252463106, e_name=encrypt_xy_sub_r_1656552498002919424_1656552239449243648, role=cn.fudata.LR_NPZ, data_len=1
2023-07-05 15:53:44,679 - [MpcPoolWorker-2:2:870] WrapUtils.py [Line:15] - DEBUG - get_event_result method execTime: 0.000 s
2023-07-05 15:53:44,690 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u540c\u6001\u751f\u6210\u4e09\u5143\u7ec4\u79cd\u5b50\u5b8c\u6210", "time": 1688543624.6884184}
2023-07-05 15:53:44,695 - [MpcPoolWorker-2:2:870] Commands.py [Line:153] - INFO - FW send event: job=1676499580252463106, target_url=https://10.86.254.244:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=triplet_gen_1656552239449243648, data_block_len=1
2023-07-05 15:53:44,695 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u68c0\u67e5\u4e09\u5143\u7ec4\u751f\u6210\u72b6\u6001", "time": 1688543624.688542}
2023-07-05 15:53:44,707 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u4efb\u52a1\u914d\u7f6e: END", "time": 1688543624.6886544}
2023-07-05 15:53:44,707 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u68c0\u67e5\u4e09\u5143\u7ec4\u751f\u6210\u72b6\u6001\u5b8c\u6210", "time": 1688543624.6886284}
2023-07-05 15:53:44,713 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b: START jobid=1676499580252463106 ", "time": 1688543624.6886914}
2023-07-05 15:53:44,716 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u6570\u636e\u51c6\u5907: START", "time": 1688543624.688711}
2023-07-05 15:53:44,717 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u5f00\u59cb\u8bfb\u53d6\u5b58\u50a8\u6570\u636e", "time": 1688543624.6887286}
2023-07-05 15:53:44,745 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u540c\u6001\u751f\u6210\u4e09\u5143\u7ec4\u79cd\u5b50\u5b8c\u6210", "time": 1688543624.6884184}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:44,750 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u68c0\u67e5\u4e09\u5143\u7ec4\u751f\u6210\u72b6\u6001", "time": 1688543624.688542}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:44,759 - [MpcPoolWorker-2:2:870] Commands.py [Line:185] - INFO - FW send event success: job=1676499580252463106, target_url=https://10.86.254.244:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=triplet_gen_1656552239449243648, data_block_len=1
2023-07-05 15:53:44,790 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u5f00\u59cb\u8bfb\u53d6\u5b58\u50a8\u6570\u636e", "time": 1688543624.6887286}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:44,790 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u68c0\u67e5\u4e09\u5143\u7ec4\u751f\u6210\u72b6\u6001\u5b8c\u6210", "time": 1688543624.6886284}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:44,791 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u4efb\u52a1\u914d\u7f6e: END", "time": 1688543624.6886544}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:44,796 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u6570\u636e\u51c6\u5907: START", "time": 1688543624.688711}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:44,804 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b: START jobid=1676499580252463106 ", "time": 1688543624.6886914}, response: {'code': '0', 'message':'OK', 'data': None, 'success': True}
2023-07-05 15:53:44,927 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u5b8c\u6210\u8bfb\u53d6\u5b58\u50a8\u6570\u636e", "time": 1688543624.9271624}
2023-07-05 15:53:44,929 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u5f00\u59cb\u6570\u636e\u5408\u6cd5\u6027\u6821\u9a8c", "time": 1688543624.9272742}
2023-07-05 15:53:44,942 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u5b8c\u6210\u6570\u636e\u5408\u6cd5\u6027\u6821\u9a8c", "time": 1688543624.9410522}
2023-07-05 15:53:44,944 - [MpcPoolWorker-2:2:870] lr_npz_hybrid_train_host.py [Line:149] - DEBUG - >>>> LR_NPZ_HYBRID 本节点数据集特征数量=34
2023-07-05 15:53:44,943 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u5f00\u59cb\u5207\u5206\u8bad\u7ec3\u96c6/\u6d4b\u8bd5\u96c6", "time": 1688543624.9411452}
2023-07-05 15:53:44,944 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u751f\u6210\u8bad\u7ec3\u96c6\u6570\u636e\u7edf\u8ba1\u4fe1\u606f", "time": 1688543624.944387}
2023-07-05 15:53:44,945 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u5212\u5206\u8bad\u7ec3\u6d4b\u8bd5\u96c6", "time": 1688543624.9411812}
2023-07-05 15:53:44,949 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u8bad\u7ec3\u96c6\u6570\u636e\u5904\u7406", "time": 1688543624.947471}
2023-07-05 15:53:44,954 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u5b8c\u6210\u5207\u5206\u8bad\u7ec3\u96c6/\u6d4b\u8bd5\u96c6", "time": 1688543624.9536204}
2023-07-05 15:53:44,957 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u6570\u636e\u51c6\u5907: END", "time": 1688543624.953694}
2023-07-05 15:53:44,958 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3: START", "time": 1688543624.9545135}
2023-07-05 15:53:44,963 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u5b8c\u6210\u8bfb\u53d6\u5b58\u50a8\u6570\u636e", "time": 1688543624.9271624}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:45,015 - [MpcPoolWorker-2:2:870] Commands.py [Line:153] - INFO - FW send event: job=1676499580252463106, target_url=https://10.86.254.244:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=bucket_format_1656552239449243648, data_block_len=1
2023-07-05 15:53:44,966 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u5f00\u59cb\u6570\u636e\u5408\u6cd5\u6027\u6821\u9a8c", "time": 1688543624.9272742}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:45,004 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u5212\u5206\u8bad\u7ec3\u6d4b\u8bd5\u96c6", "time": 1688543624.9411812}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:45,006 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u5f00\u59cb\u5207\u5206\u8bad\u7ec3\u96c6/\u6d4b\u8bd5\u96c6", "time": 1688543624.9411452}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:45,007 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u5b8c\u6210\u6570\u636e\u5408\u6cd5\u6027\u6821\u9a8c", "time": 1688543624.9410522}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:45,008 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u5b8c\u6210\u5207\u5206\u8bad\u7ec3\u96c6/\u6d4b\u8bd5\u96c6", "time": 1688543624.9536204}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:45,009 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u751f\u6210\u8bad\u7ec3\u96c6\u6570\u636e\u7edf\u8ba1\u4fe1\u606f", "time": 1688543624.944387}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:45,014 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u8bad\u7ec3\u96c6\u6570\u636e\u5904\u7406", "time": 1688543624.947471}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:45,021 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u6743\u91cd\u521d\u59cb\u5316", "time": 1688543624.9571805}
2023-07-05 15:53:45,022 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u7279\u5f81\u6570\u636e\u8fdb\u884c\u538b\u7f29\u5904\u7406", "time": 1688543624.957418}
2023-07-05 15:53:45,096 - [MpcPoolWorker-2:2:870] Commands.py [Line:185] - INFO - FW send event success: job=1676499580252463106, target_url=https://10.86.254.244:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=bucket_format_1656552239449243648, data_block_len=1
2023-07-05 15:53:45,024 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u7279\u5f81\u6570\u636e\u5206\u6279\u538b\u7f29\u5904\u7406", "time": 1688543624.9574678}
2023-07-05 15:53:45,059 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3: START", "time": 1688543624.9545135}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:45,061 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u6570\u636e\u51c6\u5907: END", "time": 1688543624.953694}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:45,163 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u7279\u5f81\u6570\u636e\u8fdb\u884c\u538b\u7f29\u5904\u7406", "time": 1688543624.957418}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:45,164 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u6743\u91cd\u521d\u59cb\u5316", "time": 1688543624.9571805}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:45,195 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u7279\u5f81\u6570\u636e\u5206\u6279\u538b\u7f29\u5904\u7406", "time": 1688543624.9574678}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:47,128 - [MainProcess:49] EventHandler.py [Line:77] - WARNING - FW web not found job event，from cache: 1676499253109334017
2023-07-05 15:53:48,131 - [MainProcess:49] WaresManager.py [Line:78] - DEBUG - register ware, server name: 10.84.61.207:8000
2023-07-05 15:53:49,013 - [LokyProcess-2:2:1:1224] __init__.py [Line:17] - INFO - LRNpzHybridWareV2 init
2023-07-05 15:53:49,013 - [LokyProcess-2:2:1:1224] AvatarApplication.py [Line:28] - INFO - FW reg ware app start: cn.fudata.LR_NPZ:v2.1.0
2023-07-05 15:53:49,022 - [LokyProcess-2:2:1:1224] AvatarApplication.py [Line:61] - INFO - FW reg ware app end: cn.fudata.LR_NPZ
2023-07-05 15:53:49,023 - [LokyProcess-2:2:1:1224] __init__.py [Line:20] - INFO - LRNpzHybridWareV2 init end
2023-07-05 15:53:49,023 - [LokyProcess-2:2:1:1224] __init__.py [Line:23] - INFO - LRNpzHybridPredictWareV2 init
2023-07-05 15:53:49,023 - [LokyProcess-2:2:1:1224] AvatarApplication.py [Line:28] - INFO - FW reg ware app start: cn.fudata.LR_NPZ_PREDICT:v2.1.0
2023-07-05 15:53:49,029 - [LokyProcess-2:2:1:1224] AvatarApplication.py [Line:61] - INFO - FW reg ware app end: cn.fudata.LR_NPZ_PREDICT
2023-07-05 15:53:49,029 - [LokyProcess-2:2:1:1224] __init__.py [Line:28] - INFO - LRNpzHybridPredictWareV2 init end
2023-07-05 15:53:49,037 - [LokyProcess-2:2:3:1226] __init__.py [Line:17] - INFO - LRNpzHybridWareV2 init
2023-07-05 15:53:49,038 - [LokyProcess-2:2:3:1226] AvatarApplication.py [Line:28] - INFO - FW reg ware app start: cn.fudata.LR_NPZ:v2.1.0
2023-07-05 15:53:49,046 - [LokyProcess-2:2:3:1226] AvatarApplication.py [Line:61] - INFO - FW reg ware app end: cn.fudata.LR_NPZ
2023-07-05 15:53:49,047 - [LokyProcess-2:2:3:1226] __init__.py [Line:20] - INFO - LRNpzHybridWareV2 init end
2023-07-05 15:53:49,047 - [LokyProcess-2:2:3:1226] __init__.py [Line:23] - INFO - LRNpzHybridPredictWareV2 init
2023-07-05 15:53:49,048 - [LokyProcess-2:2:3:1226] AvatarApplication.py [Line:28] - INFO - FW reg ware app start: cn.fudata.LR_NPZ_PREDICT:v2.1.0
2023-07-05 15:53:49,053 - [LokyProcess-2:2:3:1226] AvatarApplication.py [Line:61] - INFO - FW reg ware app end: cn.fudata.LR_NPZ_PREDICT
2023-07-05 15:53:49,053 - [LokyProcess-2:2:3:1226] __init__.py [Line:28] - INFO - LRNpzHybridPredictWareV2 init end
2023-07-05 15:53:49,073 - [LokyProcess-2:2:2:1225] __init__.py [Line:17] - INFO - LRNpzHybridWareV2 init
2023-07-05 15:53:49,074 - [LokyProcess-2:2:2:1225] AvatarApplication.py [Line:28] - INFO - FW reg ware app start: cn.fudata.LR_NPZ:v2.1.0
2023-07-05 15:53:49,081 - [LokyProcess-2:2:2:1225] AvatarApplication.py [Line:61] - INFO - FW reg ware app end: cn.fudata.LR_NPZ
2023-07-05 15:53:49,082 - [LokyProcess-2:2:2:1225] __init__.py [Line:20] - INFO - LRNpzHybridWareV2 init end
2023-07-05 15:53:49,082 - [LokyProcess-2:2:2:1225] __init__.py [Line:23] - INFO - LRNpzHybridPredictWareV2 init
2023-07-05 15:53:49,082 - [LokyProcess-2:2:2:1225] AvatarApplication.py [Line:28] - INFO - FW reg ware app start: cn.fudata.LR_NPZ_PREDICT:v2.1.0
2023-07-05 15:53:49,088 - [LokyProcess-2:2:2:1225] AvatarApplication.py [Line:61] - INFO - FW reg ware app end: cn.fudata.LR_NPZ_PREDICT
2023-07-05 15:53:49,088 - [LokyProcess-2:2:2:1225] __init__.py [Line:28] - INFO - LRNpzHybridPredictWareV2 init end
2023-07-05 15:53:49,319 - [LokyProcess-2:2:4:1227] __init__.py [Line:17] - INFO - LRNpzHybridWareV2 init
2023-07-05 15:53:49,513 - [LokyProcess-2:2:5:1228] __init__.py [Line:17] - INFO - LRNpzHybridWareV2 init
2023-07-05 15:53:49,875 - [LokyProcess-2:2:6:1229] __init__.py [Line:17] - INFO - LRNpzHybridWareV2 init
2023-07-05 15:53:49,958 - [LokyProcess-2:2:4:1227] AvatarApplication.py [Line:28] - INFO - FW reg ware app start: cn.fudata.LR_NPZ:v2.1.0
2023-07-05 15:53:49,958 - [LokyProcess-2:2:5:1228] AvatarApplication.py [Line:28] - INFO - FW reg ware app start: cn.fudata.LR_NPZ:v2.1.0
2023-07-05 15:53:49,959 - [LokyProcess-2:2:6:1229] AvatarApplication.py [Line:28] - INFO - FW reg ware app start: cn.fudata.LR_NPZ:v2.1.0
2023-07-05 15:53:49,968 - [LokyProcess-2:2:5:1228] AvatarApplication.py [Line:61] - INFO - FW reg ware app end: cn.fudata.LR_NPZ
2023-07-05 15:53:49,969 - [LokyProcess-2:2:5:1228] __init__.py [Line:20] - INFO - LRNpzHybridWareV2 init end
2023-07-05 15:53:49,968 - [LokyProcess-2:2:4:1227] AvatarApplication.py [Line:61] - INFO - FW reg ware app end: cn.fudata.LR_NPZ
2023-07-05 15:53:49,969 - [LokyProcess-2:2:5:1228] __init__.py [Line:23] - INFO - LRNpzHybridPredictWareV2 init
2023-07-05 15:53:49,969 - [LokyProcess-2:2:4:1227] __init__.py [Line:20] - INFO - LRNpzHybridWareV2 init end
2023-07-05 15:53:49,969 - [LokyProcess-2:2:6:1229] AvatarApplication.py [Line:61] - INFO - FW reg ware app end: cn.fudata.LR_NPZ
2023-07-05 15:53:49,969 - [LokyProcess-2:2:4:1227] __init__.py [Line:23] - INFO - LRNpzHybridPredictWareV2 init
2023-07-05 15:53:49,969 - [LokyProcess-2:2:5:1228] AvatarApplication.py [Line:28] - INFO - FW reg ware app start: cn.fudata.LR_NPZ_PREDICT:v2.1.0
2023-07-05 15:53:49,970 - [LokyProcess-2:2:6:1229] __init__.py [Line:20] - INFO - LRNpzHybridWareV2 init end
2023-07-05 15:53:49,970 - [LokyProcess-2:2:6:1229] __init__.py [Line:23] - INFO - LRNpzHybridPredictWareV2 init
2023-07-05 15:53:49,970 - [LokyProcess-2:2:4:1227] AvatarApplication.py [Line:28] - INFO - FW reg ware app start: cn.fudata.LR_NPZ_PREDICT:v2.1.0
2023-07-05 15:53:49,970 - [LokyProcess-2:2:6:1229] AvatarApplication.py [Line:28] - INFO - FW reg ware app start: cn.fudata.LR_NPZ_PREDICT:v2.1.0
2023-07-05 15:53:49,975 - [LokyProcess-2:2:5:1228] AvatarApplication.py [Line:61] - INFO - FW reg ware app end: cn.fudata.LR_NPZ_PREDICT
2023-07-05 15:53:49,975 - [LokyProcess-2:2:5:1228] __init__.py [Line:28] - INFO - LRNpzHybridPredictWareV2 init end
2023-07-05 15:53:49,976 - [LokyProcess-2:2:4:1227] AvatarApplication.py [Line:61] - INFO - FW reg ware app end: cn.fudata.LR_NPZ_PREDICT
2023-07-05 15:53:49,976 - [LokyProcess-2:2:6:1229] AvatarApplication.py [Line:61] - INFO - FW reg ware app end: cn.fudata.LR_NPZ_PREDICT
2023-07-05 15:53:49,976 - [LokyProcess-2:2:4:1227] __init__.py [Line:28] - INFO - LRNpzHybridPredictWareV2 init end
2023-07-05 15:53:49,976 - [LokyProcess-2:2:6:1229] __init__.py [Line:28] - INFO - LRNpzHybridPredictWareV2 init end
2023-07-05 15:53:50,128 - [MainProcess:49] EventHandler.py [Line:77] - WARNING - FW web not found job event，from cache: 1676499253109334017
2023-07-05 15:53:50,484 - [MpcPoolWorker-2:2:870] Commands.py [Line:153] - INFO - FW send event: job=1676499580252463106, target_url=https://10.86.143.51:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=sample_to_bin_index_handler_1656552239449243648, data_block_len=1
2023-07-05 15:53:50,482 - [MpcPoolWorker-2:2:870] lr_npz_hybrid_base.py [Line:1098] - DEBUG - >>>> yq k1 type(x)=<class 'numpy.ndarray'>
2023-07-05 15:53:50,485 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u7279\u5f81\u5206\u7bb1\u72b6\u6001\u540c\u6b65", "time": 1688543630.482076}
2023-07-05 15:53:50,485 - [MpcPoolWorker-2:2:870] Commands.py [Line:153] - INFO - FW send event: job=1676499580252463106, target_url=https://10.86.254.244:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=feature_to_bin_handler_1656552239449243648, data_block_len=1
2023-07-05 15:53:50,488 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u5f00\u59cb\u7b2cEpoch0\u8f6e\u8bad\u7ec3", "time": 1688543630.4825573}
2023-07-05 15:53:50,494 - [MpcPoolWorker-2:2:870] lr_npz_hybrid_base.py [Line:1103] - DEBUG - >>>> yq k12 type(x)=<class 'numpy.ndarray'>
2023-07-05 15:53:50,489 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u4e2d - Epoch0 - Batch0 - Start0 - END1000", "time": 1688543630.4826086}
2023-07-05 15:53:50,495 - [MpcPoolWorker-2:2:870] Commands.py [Line:185] - INFO - FW send event success: job=1676499580252463106, target_url=https://10.86.143.51:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=sample_to_bin_index_handler_1656552239449243648, data_block_len=1
2023-07-05 15:53:50,502 - [MpcPoolWorker-2:2:870] lr_npz_hybrid_train_host.py [Line:281] - DEBUG - >>>> LR_NPZ_HYBRID h_save_remote_file_id=df_h_pow_e_val_1676499580252463106_0_0
2023-07-05 15:53:50,521 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u7279\u5f81\u5206\u7bb1\u72b6\u6001\u540c\u6b65", "time": 1688543630.482076}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:50,530 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u4e2d - Epoch0 - Batch0 - Start0 - END1000", "time": 1688543630.4826086}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:50,533 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_HYBRID \u5f00\u59cb\u7b2cEpoch0\u8f6e\u8bad\u7ec3", "time": 1688543630.4825573}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:50,538 - [MpcPoolWorker-2:2:870] Commands.py [Line:185] - INFO - FW send event success: job=1676499580252463106, target_url=https://10.86.254.244:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=feature_to_bin_handler_1656552239449243648, data_block_len=1
2023-07-05 15:53:50,659 - [MpcPoolWorker-2:2:870] lr_npz_hybrid_train_host.py [Line:286] - DEBUG - >>>> LR_NPZ_HYBRID h_sigmoid_factor_batch_remote_id=s3://dev-sf2-lts-n2/permanent/nid_1656552239449243648/pid_1656565751110172672/fid_1676489357768925185/jid_1676490320432996353/tid_1676491313195393025/dataset/output_missing1/df_h_pow_e_val_1676499580252463106_0_0
2023-07-05 15:53:50,660 - [MpcPoolWorker-2:2:870] EventListener.py [Line:144] - INFO - FW get_event_result: job=1676499580252463106, e_name=op_dw_save_1656552239449243648_0_0, role=cn.fudata.LR_NPZ, to=7200s
2023-07-05 15:53:50,660 - [MpcPoolWorker-2:2:870] Commands.py [Line:153] - INFO - FW send event: job=1676499580252463106, target_url=https://10.86.254.244:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=sigmoid_factor_0_0_1656552239449243648, data_block_len=1
2023-07-05 15:53:50,661 - [MpcPoolWorker-2:2:870] EventListener.py [Line:99] - INFO - FW get_event_result set[[single]] data local3: jobid=1676499580252463106, e_name=encrypt_xy_sub_r_1656551243780194304_1656552498002919424/get=op_dw_save_1656552239449243648_0_0, ware_id=cn.fudata.LR_NPZ
2023-07-05 15:53:50,660 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_Hybrid \u63a5\u6536\u672c\u5730\u6a21\u578b\u53c2\u6570\u68af\u5ea6dw\u53e5\u67c4", "time": 1688543630.6600523}
2023-07-05 15:53:50,690 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "info", "data": ">>>> LR_NPZ_Hybrid \u63a5\u6536\u672c\u5730\u6a21\u578b\u53c2\u6570\u68af\u5ea6dw\u53e5\u67c4", "time": 1688543630.6600523}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:50,705 - [MpcPoolWorker-2:2:870] Commands.py [Line:185] - INFO - FW send event success: job=1676499580252463106, target_url=https://10.86.254.244:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=sigmoid_factor_0_0_1656552239449243648, data_block_len=1
2023-07-05 15:53:52,078 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "error", "data": ">>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 377, in train\\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\\n  File \"fmpcbase/protocol/npz/npz.py\", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\\n  File \"fmpcbase/protocol/npz/npz.py\", line 498, infmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\\n  File \"fmpcbase/protocol/npz/npz.py\", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\\n  File \"fmpcbase/protocol/npz/npz.py\", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\\n  File \"fmpcbase/protocol/npz/npz.py\", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\\n  File \"fmpcbase/tensor/native.py\", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\\n  File \"/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 1175, in shape\\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 73, in do_start\\n    self.train()  # \u4f5c\u4e3a\u53d1\u8d77\u65b9\u8fdb\u884c\u6a21\u578b\u8bad\u7ec3\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 508, in train\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/fmpc/base/Algorithm.py\", line 103, in action\\n    self.start()\\n  File \"/data/fmpc/wares/common/base_algorithm.py\", line 337, in start\\n    self.do_start()\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 102, in do_start\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n'})", "time": 1688543632.0774338}
2023-07-05 15:53:52,081 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "error", "data": ">>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:Traceback (most recent call last):\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 444, in train\n    dw_shape_0, dw_shape_1, dw_remote_id = self.algo_data_transfer.op_dw_save.get(self.listener,\n  File \"/data/fmpc/wares/common/algo_data_transfer.py\", line 130, in get\n    ret = self._do_get(listener, full_name, timeout)\n  File \"/data/fmpc/wares/common/local_develop_helper.py\", line 48, in _do_get\n    return super()._do_get(listener, name, timeout)\n  File \"/data/fmpc/wares/common/algo_data_transfer.py\", line 195, in _do_get\n    result, ename = listener.get_event_pickle_result(name, timeout)\n  File \"/data/fmpc/fmpc/base/EventListener.py\", line 29,in get_event_pickle_result\n    result_data, r_name = self.get_event_result(e_name, timeout)\n  File \"/data/fmpc/fmpc/utils/WrapUtils.py\", line 13, in wrap\n    result = func(*args, **kwargs)\n  File \"/data/fmpc/fmpc/base/EventListener.py\", line 165, in get_event_result\n    return_flag, r_data, e_name =self._handle_event_dt_from_transfer(event_dt, e_name)\n  File \"/data/fmpc/fmpc/base/EventListener.py\", line 91, in _handle_event_dt_from_transfer\n    raise RuntimeError(r_name, pickle.loads(r_data))\nRuntimeError: ('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 377, in train\\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\\n  File \"fmpcbase/protocol/npz/npz.py\", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\\n  File \"fmpcbase/protocol/npz/npz.py\", line 498, infmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\\n  File \"fmpcbase/protocol/npz/npz.py\", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\\n  File \"fmpcbase/protocol/npz/npz.py\", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\\n  File \"fmpcbase/protocol/npz/npz.py\", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\\n  File \"fmpcbase/tensor/native.py\", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\\n  File \"/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 1175, in shape\\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 73, in do_start\\n    self.train()  # \u4f5c\u4e3a\u53d1\u8d77\u65b9\u8fdb\u884c\u6a21\u578b\u8bad\u7ec3\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 508, in train\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/fmpc/base/Algorithm.py\", line 103, in action\\n    self.start()\\n  File \"/data/fmpc/wares/common/base_algorithm.py\", line 337, in start\\n    self.do_start()\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 102, in do_start\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n'})\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 78, in do_start\n    self.train()  # \u4f5c\u4e3a\u53c2\u4e0e\u65b9\u8fdb\u884c\u6a21\u578b\u8bad\u7ec3\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 508, in train\n    raise RuntimeError('>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:{}'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 377, in train\\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\\n  File \"fmpcbase/protocol/npz/npz.py\", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\\n  File \"fmpcbase/protocol/npz/npz.py\", line 498, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\\n  File \"fmpcbase/protocol/npz/npz.py\", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\\n  File \"fmpcbase/protocol/npz/npz.py\", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\\n  File \"fmpcbase/protocol/npz/npz.py\", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\\n  File \"fmpcbase/tensor/native.py\", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\\n  File \"/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 1175, in shape\\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 73, in do_start\\n    self.train()  # \u4f5c\u4e3a\u53d1\u8d77\u65b9\u8fdb\u884c\u6a21\u578b\u8bad\u7ec3\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 508, in train\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/fmpc/base/Algorithm.py\", line 103, in action\\n    self.start()\\n  File \"/data/fmpc/wares/common/base_algorithm.py\", line 337, in start\\n    self.do_start()\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 102, in do_start\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n'})\n", "time": 1688543632.0813506}
2023-07-05 15:53:52,082 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "error", "data": ">>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 377, in train\\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\\n  File \"fmpcbase/protocol/npz/npz.py\", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\\n  File \"fmpcbase/protocol/npz/npz.py\", line 498, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\\n  File \"fmpcbase/protocol/npz/npz.py\", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\\n  File \"fmpcbase/protocol/npz/npz.py\", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\\n  File \"fmpcbase/protocol/npz/npz.py\", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\\n  File \"fmpcbase/tensor/native.py\", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\\n  File \"/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 1175, in shape\\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling ofthe above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 73, in do_start\\n    self.train()  # \u4f5c\u4e3a\u53d1\u8d77\u65b9\u8fdb\u884c\u6a21\u578b\u8bad\u7ec3\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 508, in train\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/fmpc/base/Algorithm.py\", line 103, in action\\n    self.start()\\n  File \"/data/fmpc/wares/common/base_algorithm.py\", line 337, in start\\n    self.do_start()\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 102, in do_start\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n'})", "time": 1688543632.0814168}
2023-07-05 15:53:52,085 - [MpcPoolWorker-2:2:870] Commands.py [Line:153] - INFO - FW send event: job=1676499580252463106, target_url=https://10.86.254.244:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=Job_Fin, data_block_len=1
2023-07-05 15:53:52,092 - [MpcPoolWorker-2:2:870] Commands.py [Line:185] - INFO - FW send event success: job=1676499580252463106, target_url=https://10.86.254.244:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=Job_Fin, data_block_len=1
2023-07-05 15:53:52,092 - [MpcPoolWorker-2:2:870] HttpComms.py [Line:34] - DEBUG - target_url:https://10.86.29.50:10000/gateway/v2/ware/receive, cur_gateway_url:https://10.86.29.50:10000, gateway_url:10.84.61.207:8000, replaced url: http://10.84.61.207:8000/gateway/v2/ware/receive
2023-07-05 15:53:52,092 - [MpcPoolWorker-2:2:870] Commands.py [Line:153] - INFO - FW send event: job=1676499580252463106, target_url=http://10.84.61.207:8000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=Job_Fin, data_block_len=1
2023-07-05 15:53:52,095 - [MpcPoolWorker-2:2:870] Commands.py [Line:185] - INFO - FW send event success: job=1676499580252463106, target_url=http://10.84.61.207:8000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=Job_Fin, data_block_len=1
2023-07-05 15:53:52,095 - [MpcPoolWorker-2:2:870] Commands.py [Line:153] - INFO - FW send event: job=1676499580252463106, target_url=https://10.86.143.51:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=Job_Fin, data_block_len=1
2023-07-05 15:53:52,100 - [MpcPoolWorker-2:2:870] Commands.py [Line:185] - INFO - FW send event success: job=1676499580252463106, target_url=https://10.86.143.51:10000/gateway/v2/ware/receive, ware_id=cn.fudata.LR_NPZ, e_name=Job_Fin, data_block_len=1
2023-07-05 15:53:52,102 - [MpcPoolWorker-2:2:870] base_ware.py [Line:104] - ERROR - Traceback (most recent call last):
  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 444, in train
    dw_shape_0, dw_shape_1, dw_remote_id = self.algo_data_transfer.op_dw_save.get(self.listener,
  File "/data/fmpc/wares/common/algo_data_transfer.py", line 130, in get
    ret = self._do_get(listener, full_name, timeout)
  File "/data/fmpc/wares/common/local_develop_helper.py", line 48, in _do_get
    return super()._do_get(listener, name, timeout)
  File "/data/fmpc/wares/common/algo_data_transfer.py", line 195, in _do_get
    result, ename = listener.get_event_pickle_result(name, timeout)
  File "/data/fmpc/fmpc/base/EventListener.py", line 29, in get_event_pickle_result
    result_data, r_name = self.get_event_result(e_name, timeout)
  File "/data/fmpc/fmpc/utils/WrapUtils.py", line 13, in wrap
    result = func(*args, **kwargs)
  File "/data/fmpc/fmpc/base/EventListener.py", line 165, in get_event_result
    return_flag, r_data, e_name = self._handle_event_dt_from_transfer(event_dt, e_name)
  File "/data/fmpc/fmpc/base/EventListener.py", line 91, in _handle_event_dt_from_transfer
    raise RuntimeError(r_name, pickle.loads(r_data))
RuntimeError: ('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 377, in train\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\n  File "fmpcbase/protocol/npz/npz.py", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\n  File "fmpcbase/protocol/npz/npz.py", line 498, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 516,in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\n  File "fmpcbase/protocol/npz/npz.py", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\n  File "fmpcbase/protocol/npz/npz.py", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\n  File "fmpcbase/protocol/npz/npz.py", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\n  File "fmpcbase/tensor/native.py", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\n  File "/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 1175, in shape\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 73, in do_start\n    self.train()  # 作为发起方进行模型训练\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 508, in train\n    raise RuntimeError(\'>>>> LR_NPZ_HYBRID 模型训练异常:{}\'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID 模型训练异常:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/fmpc/fmpc/base/Algorithm.py", line 103, in action\n    self.start()\n  File "/data/fmpc/wares/common/base_algorithm.py", line 337, in start\n    self.do_start()\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 102, in do_start\n    raise RuntimeError(\'>>>> LR_NPZ_HYBRID 主任务流程出错:{}\'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID 主任务流程出错:>>>> LR_NPZ_HYBRID 模型训练异常:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 78, in do_start
    self.train()  # 作为参与方进行模型训练
  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 508, in train
    raise RuntimeError('>>>> LR_NPZ_HYBRID 模型训练异常:{}'.format(ex))
RuntimeError: >>>> LR_NPZ_HYBRID 模型训练异常:('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 377, in train\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\n  File "fmpcbase/protocol/npz/npz.py", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\n  File "fmpcbase/protocol/npz/npz.py", line 498, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\n  File "fmpcbase/protocol/npz/npz.py", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\n  File "fmpcbase/protocol/npz/npz.py", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\n  File "fmpcbase/protocol/npz/npz.py", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\n  File "fmpcbase/tensor/native.py", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\n  File "/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 1175, in shape\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requiresa multiple of 32\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 73, in do_start\n    self.train()  # 作为发起方进行模型训练\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 508, in train\n    raise RuntimeError(\'>>>> LR_NPZ_HYBRID 模型训练异常:{}\'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID 模型训练异常:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/fmpc/fmpc/base/Algorithm.py", line 103, in action\n    self.start()\n  File "/data/fmpc/wares/common/base_algorithm.py", line 337, in start\n    self.do_start()\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 102, in do_start\n    raise RuntimeError(\'>>>> LR_NPZ_HYBRID 主任务流程出错:{}\'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID 主任务流程出错:>>>> LR_NPZ_HYBRID 模型训练异常:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/fmpc/wares/common/base_ware.py", line 71, in start
    self.do_start(job, ctx, **kwargs)
  File "/data/fmpc/wares/common/base_ware.py", line 123, in do_start
    algo.action(job, ctx)
  File "/data/fmpc/fmpc/base/Algorithm.py", line 105, in action
    self.fin(e)
  File "/data/fmpc/wares/common/base_algorithm.py", line 156, in fin
    raise e
  File "/data/fmpc/fmpc/base/Algorithm.py", line 103, in action
    self.start()
  File "/data/fmpc/wares/common/base_algorithm.py", line 337, in start
    self.do_start()
  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 102, in do_start
    raise RuntimeError('>>>> LR_NPZ_HYBRID 主任务流程出错:{}'.format(ex))
RuntimeError: >>>> LR_NPZ_HYBRID 主任务流程出错:>>>> LR_NPZ_HYBRID 模型训练异常:('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 377, in train\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\n  File "fmpcbase/protocol/npz/npz.py", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\n  File "fmpcbase/protocol/npz/npz.py", line 498, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\n  File "fmpcbase/protocol/npz/npz.py", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\n  File "fmpcbase/protocol/npz/npz.py", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\n  File "fmpcbase/protocol/npz/npz.py", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\n  File "fmpcbase/tensor/native.py", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\n  File "/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 1175, in shape\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 73, in do_start\n    self.train()  # 作为发起方进行模型训练\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 508, in train\n    raise RuntimeError(\'>>>> LR_NPZ_HYBRID 模型训练异常:{}\'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID 模型训练异常:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of32\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/fmpc/fmpc/base/Algorithm.py", line 103, in action\n    self.start()\n  File "/data/fmpc/wares/common/base_algorithm.py", line 337, in start\n    self.do_start()\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 102, in do_start\n    raise RuntimeError(\'>>>> LR_NPZ_HYBRID 主任务流程出错:{}\'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID 主任务流程出错:>>>> LR_NPZ_HYBRID 模型训练异常:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n'})

2023-07-05 15:53:52,102 - [MpcPoolWorker-2:2:870] base_ware.py [Line:254] - DEBUG - workbench log, job_id: 1676499580252463106, log_level: error,log_data: [InternalWareError] 组件内部错误。  cause: RuntimeError, >>>> LR_NPZ_HYBRID 主任务流程出错:>>>> LR_NPZ_HYBRID 模型训练异常:('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 377, in train\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\n  File "fmpcbase/protocol/npz/npz.py", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\n File "fmpcbase/protocol/npz/npz.py", line 498, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\n  File "fmpcbase/protocol/npz/npz.py", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\n  File "fmpcbase/protocol/npz/npz.py", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\n  File "fmpcbase/protocol/npz/npz.py", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\n  File "fmpcbase/tensor/native.py", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\n  File "/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 1175, in shape\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n\nDuring handling of the above exception, another exceptionoccurred:\n\nTraceback (most recent call last):\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 73, in do_start\n    self.train()  # 作为发起方进行模型训练\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 508, in train\n    raise RuntimeError(\'>>>> LR_NPZ_HYBRID 模型训练异常:{}\'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID 模型训练异常:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/fmpc/fmpc/base/Algorithm.py", line 103, in action\n    self.start()\n  File "/data/fmpc/wares/common/base_algorithm.py", line 337, in start\n    self.do_start()\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 102, in do_start\n    raise RuntimeError(\'>>>> LR_NPZ_HYBRID 主任务流程出错:{}\'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID 主任务流程出错:>>>> LR_NPZ_HYBRID 模型训练异常:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n'}), log_type: local
2023-07-05 15:53:52,102 - [MpcPoolWorker-2:2:870] base_ware.py [Line:254] - DEBUG - workbench log, job_id: 1676499580252463106, log_level: error,log_data: Traceback (most recent call last):
  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 444, in train
    dw_shape_0, dw_shape_1, dw_remote_id = self.algo_data_transfer.op_dw_save.get(self.listener,
  File "/data/fmpc/wares/common/algo_data_transfer.py", line 130, in get
    ret = self._do_get(listener, full_name, timeout)
  File "/data/fmpc/wares/common/local_develop_helper.py", line 48, in _do_get
    return super()._do_get(listener, name, timeout)
  File "/data/fmpc/wares/common/algo_data_transfer.py", line 195, in _do_get
    result, ename = listener.get_event_pickle_result(name, timeout)
  File "/data/fmpc/fmpc/base/EventListener.py", line 29, in get_event_pickle_result
    result_data, r_name = self.get_event_result(e_name, timeout)
  File "/data/fmpc/fmpc/utils/WrapUtils.py", line 13, in wrap
    result = func(*args, **kwargs)
  File "/data/fmpc/fmpc/base/EventListener.py", line 165, in get_event_result
    return_flag, r_data, e_name = self._handle_event_dt_from_transfer(event_dt, e_name)
  File "/data/fmpc/fmpc/base/EventListener.py", line 91, in _handle_event_dt_from_transfer
    raise RuntimeError(r_name, pickle.loads(r_data))
RuntimeError: ('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 377, in train\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\n  File "fmpcbase/protocol/npz/npz.py", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\n  File "fmpcbase/protocol/npz/npz.py", line 498, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 516,in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\n  File "fmpcbase/protocol/npz/npz.py", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\n  File "fmpcbase/protocol/npz/npz.py", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\n  File "fmpcbase/protocol/npz/npz.py", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\n  File "fmpcbase/tensor/native.py", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\n  File "/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 1175, in shape\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 73, in do_start\n    self.train()  # 作为发起方进行模型训练\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 508, in train\n    raise RuntimeError(\'>>>> LR_NPZ_HYBRID 模型训练异常:{}\'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID 模型训练异常:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/fmpc/fmpc/base/Algorithm.py", line 103, in action\n    self.start()\n  File "/data/fmpc/wares/common/base_algorithm.py", line 337, in start\n    self.do_start()\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 102, in do_start\n    raise RuntimeError(\'>>>> LR_NPZ_HYBRID 主任务流程出错:{}\'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID 主任务流程出错:>>>> LR_NPZ_HYBRID 模型训练异常:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 78, in do_start
    self.train()  # 作为参与方进行模型训练
  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 508, in train
    raise RuntimeError('>>>> LR_NPZ_HYBRID 模型训练异常:{}'.format(ex))
RuntimeError: >>>> LR_NPZ_HYBRID 模型训练异常:('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 377, in train\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\n  File "fmpcbase/protocol/npz/npz.py", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\n  File "fmpcbase/protocol/npz/npz.py", line 498, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\n  File "fmpcbase/protocol/npz/npz.py", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\n  File "fmpcbase/protocol/npz/npz.py", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\n  File "fmpcbase/protocol/npz/npz.py", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\n  File "fmpcbase/tensor/native.py", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\n  File "/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 1175, in shape\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requiresa multiple of 32\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 73, in do_start\n    self.train()  # 作为发起方进行模型训练\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 508, in train\n    raise RuntimeError(\'>>>> LR_NPZ_HYBRID 模型训练异常:{}\'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID 模型训练异常:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/fmpc/fmpc/base/Algorithm.py", line 103, in action\n    self.start()\n  File "/data/fmpc/wares/common/base_algorithm.py", line 337, in start\n    self.do_start()\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 102, in do_start\n    raise RuntimeError(\'>>>> LR_NPZ_HYBRID 主任务流程出错:{}\'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID 主任务流程出错:>>>> LR_NPZ_HYBRID 模型训练异常:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/fmpc/wares/common/base_ware.py", line 71, in start
    self.do_start(job, ctx, **kwargs)
  File "/data/fmpc/wares/common/base_ware.py", line 123, in do_start
    algo.action(job, ctx)
  File "/data/fmpc/fmpc/base/Algorithm.py", line 105, in action
    self.fin(e)
  File "/data/fmpc/wares/common/base_algorithm.py", line 156, in fin
    raise e
  File "/data/fmpc/fmpc/base/Algorithm.py", line 103, in action
    self.start()
  File "/data/fmpc/wares/common/base_algorithm.py", line 337, in start
    self.do_start()
  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 102, in do_start
    raise RuntimeError('>>>> LR_NPZ_HYBRID 主任务流程出错:{}'.format(ex))
RuntimeError: >>>> LR_NPZ_HYBRID 主任务流程出错:>>>> LR_NPZ_HYBRID 模型训练异常:('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 377, in train\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\n  File "fmpcbase/protocol/npz/npz.py", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\n  File "fmpcbase/protocol/npz/npz.py", line 498, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\n  File "fmpcbase/protocol/npz/npz.py", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\n  File "fmpcbase/protocol/npz/npz.py", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\n  File "fmpcbase/protocol/npz/npz.py", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\n  File "fmpcbase/tensor/native.py", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\n  File "/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 1175, in shape\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 73, in do_start\n    self.train()  # 作为发起方进行模型训练\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 508, in train\n    raise RuntimeError(\'>>>> LR_NPZ_HYBRID 模型训练异常:{}\'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID 模型训练异常:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of32\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/fmpc/fmpc/base/Algorithm.py", line 103, in action\n    self.start()\n  File "/data/fmpc/wares/common/base_algorithm.py", line 337, in start\n    self.do_start()\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 102, in do_start\n    raise RuntimeError(\'>>>> LR_NPZ_HYBRID 主任务流程出错:{}\'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID 主任务流程出错:>>>> LR_NPZ_HYBRID 模型训练异常:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n'})
, log_type: local
2023-07-05 15:53:52,103 - [MpcPoolWorker-2:2:870] WareExecutor.py [Line:89] - ERROR - Traceback (most recent call last):
  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 444, in train
    dw_shape_0, dw_shape_1, dw_remote_id = self.algo_data_transfer.op_dw_save.get(self.listener,
  File "/data/fmpc/wares/common/algo_data_transfer.py", line 130, in get
    ret = self._do_get(listener, full_name, timeout)
  File "/data/fmpc/wares/common/local_develop_helper.py", line 48, in _do_get
    return super()._do_get(listener, name, timeout)
  File "/data/fmpc/wares/common/algo_data_transfer.py", line 195, in _do_get
    result, ename = listener.get_event_pickle_result(name, timeout)
  File "/data/fmpc/fmpc/base/EventListener.py", line 29, in get_event_pickle_result
    result_data, r_name = self.get_event_result(e_name, timeout)
  File "/data/fmpc/fmpc/utils/WrapUtils.py", line 13, in wrap
    result = func(*args, **kwargs)
  File "/data/fmpc/fmpc/base/EventListener.py", line 165, in get_event_result
    return_flag, r_data, e_name = self._handle_event_dt_from_transfer(event_dt, e_name)
  File "/data/fmpc/fmpc/base/EventListener.py", line 91, in _handle_event_dt_from_transfer
    raise RuntimeError(r_name, pickle.loads(r_data))
RuntimeError: ('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 377, in train\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\n  File "fmpcbase/protocol/npz/npz.py", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\n  File "fmpcbase/protocol/npz/npz.py", line 498, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 516,in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\n  File "fmpcbase/protocol/npz/npz.py", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\n  File "fmpcbase/protocol/npz/npz.py", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\n  File "fmpcbase/protocol/npz/npz.py", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\n  File "fmpcbase/tensor/native.py", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\n  File "/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 1175, in shape\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 73, in do_start\n    self.train()  # 作为发起方进行模型训练\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 508, in train\n    raise RuntimeError(\'>>>> LR_NPZ_HYBRID 模型训练异常:{}\'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID 模型训练异常:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/fmpc/fmpc/base/Algorithm.py", line 103, in action\n    self.start()\n  File "/data/fmpc/wares/common/base_algorithm.py", line 337, in start\n    self.do_start()\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 102, in do_start\n    raise RuntimeError(\'>>>> LR_NPZ_HYBRID 主任务流程出错:{}\'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID 主任务流程出错:>>>> LR_NPZ_HYBRID 模型训练异常:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 78, in do_start
    self.train()  # 作为参与方进行模型训练
  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 508, in train
    raise RuntimeError('>>>> LR_NPZ_HYBRID 模型训练异常:{}'.format(ex))
RuntimeError: >>>> LR_NPZ_HYBRID 模型训练异常:('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 377, in train\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\n  File "fmpcbase/protocol/npz/npz.py", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\n  File "fmpcbase/protocol/npz/npz.py", line 498, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\n  File "fmpcbase/protocol/npz/npz.py", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\n  File "fmpcbase/protocol/npz/npz.py", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\n  File "fmpcbase/protocol/npz/npz.py", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\n  File "fmpcbase/tensor/native.py", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\n  File "/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 1175, in shape\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requiresa multiple of 32\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 73, in do_start\n    self.train()  # 作为发起方进行模型训练\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 508, in train\n    raise RuntimeError(\'>>>> LR_NPZ_HYBRID 模型训练异常:{}\'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID 模型训练异常:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/fmpc/fmpc/base/Algorithm.py", line 103, in action\n    self.start()\n  File "/data/fmpc/wares/common/base_algorithm.py", line 337, in start\n    self.do_start()\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 102, in do_start\n    raise RuntimeError(\'>>>> LR_NPZ_HYBRID 主任务流程出错:{}\'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID 主任务流程出错:>>>> LR_NPZ_HYBRID 模型训练异常:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/fmpc/wares/common/base_ware.py", line 71, in start
    self.do_start(job, ctx, **kwargs)
  File "/data/fmpc/wares/common/base_ware.py", line 123, in do_start
    algo.action(job, ctx)
  File "/data/fmpc/fmpc/base/Algorithm.py", line 105, in action
    self.fin(e)
  File "/data/fmpc/wares/common/base_algorithm.py", line 156, in fin
    raise e
  File "/data/fmpc/fmpc/base/Algorithm.py", line 103, in action
    self.start()
  File "/data/fmpc/wares/common/base_algorithm.py", line 337, in start
    self.do_start()
  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 102, in do_start
    raise RuntimeError('>>>> LR_NPZ_HYBRID 主任务流程出错:{}'.format(ex))
RuntimeError: >>>> LR_NPZ_HYBRID 主任务流程出错:>>>> LR_NPZ_HYBRID 模型训练异常:('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 377, in train\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\n  File "fmpcbase/protocol/npz/npz.py", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\n  File "fmpcbase/protocol/npz/npz.py", line 498, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\n  File "fmpcbase/protocol/npz/npz.py", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\n  File "fmpcbase/protocol/npz/npz.py", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\n  File "fmpcbase/protocol/npz/npz.py", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\n  File "fmpcbase/tensor/native.py", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\n  File "/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 1175, in shape\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 73, in do_start\n    self.train()  # 作为发起方进行模型训练\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 508, in train\n    raise RuntimeError(\'>>>> LR_NPZ_HYBRID 模型训练异常:{}\'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID 模型训练异常:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of32\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/fmpc/fmpc/base/Algorithm.py", line 103, in action\n    self.start()\n  File "/data/fmpc/wares/common/base_algorithm.py", line 337, in start\n    self.do_start()\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 102, in do_start\n    raise RuntimeError(\'>>>> LR_NPZ_HYBRID 主任务流程出错:{}\'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID 主任务流程出错:>>>> LR_NPZ_HYBRID 模型训练异常:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n'})

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/fmpc/fmpc/base/WareExecutor.py", line 85, in _create_and_execute
    ware.start(job, ctx)
  File "/data/fmpc/wares/common/base_ware.py", line 87, in start
    raise ex from e
wares.common.fmpc_error.InternalWareError: [InternalWareError] 组件内部错误。  cause: RuntimeError, >>>> LR_NPZ_HYBRID 主任务流程出错:>>>> LR_NPZ_HYBRID 模型训练异常:('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 377, in train\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\n  File "fmpcbase/protocol/npz/npz.py", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\n  File "fmpcbase/protocol/npz/npz.py", line 498, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\n  File "fmpcbase/protocol/npz/npz.py", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\n  File "fmpcbase/protocol/npz/npz.py", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\n  File "fmpcbase/protocol/npz/npz.py", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\n  File "fmpcbase/protocol/npz/npz.py", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\n  File "fmpcbase/tensor/native.py", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\n  File "/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 1175, in shape\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 73, in do_start\n    self.train()  # 作为发起方进行模型训练\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 508, in train\n    raise RuntimeError(\'>>>> LR_NPZ_HYBRID 模型训练异常:{}\'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID 模型训练异常:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/fmpc/fmpc/base/Algorithm.py", line 103, in action\n    self.start()\n  File "/data/fmpc/wares/common/base_algorithm.py", line 337, in start\n    self.do_start()\n  File "/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py", line 102, in do_start\n    raise RuntimeError(\'>>>> LR_NPZ_HYBRID 主任务流程出错:{}\'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID 主任务流程出错:>>>> LR_NPZ_HYBRID 模型训练异常:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\n'})

2023-07-05 15:53:52,104 - [MpcPoolWorker-2:2:870] ResourceInit.py [Line:148] - DEBUG - [process_exit_check]delete thread pool
2023-07-05 15:53:52,103 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "error", "data": "[InternalWareError] \u7ec4\u4ef6\u5185\u90e8\u9519\u8bef\u3002  cause: RuntimeError, >>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 377, in train\\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\\n  File \"fmpcbase/protocol/npz/npz.py\", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\\n  File \"fmpcbase/protocol/npz/npz.py\", line 498, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\\n  File \"fmpcbase/protocol/npz/npz.py\", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\\n  File \"fmpcbase/protocol/npz/npz.py\", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\\n  File \"fmpcbase/protocol/npz/npz.py\", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\\n  File \"fmpcbase/tensor/native.py\", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\\n  File \"/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 1175, in shape\\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 73, in do_start\\n    self.train()  # \u4f5c\u4e3a\u53d1\u8d77\u65b9\u8fdb\u884c\u6a21\u578b\u8bad\u7ec3\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 508, in train\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/fmpc/base/Algorithm.py\", line 103, in action\\n    self.start()\\n  File \"/data/fmpc/wares/common/base_algorithm.py\", line 337, in start\\n    self.do_start()\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 102, in do_start\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n'})", "time": 1688543632.102423}
2023-07-05 15:53:52,104 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:35] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "error", "data": "Traceback (most recent call last):\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 444, in train\n    dw_shape_0, dw_shape_1, dw_remote_id = self.algo_data_transfer.op_dw_save.get(self.listener,\n  File \"/data/fmpc/wares/common/algo_data_transfer.py\", line 130, in get\n    ret = self._do_get(listener, full_name, timeout)\n  File \"/data/fmpc/wares/common/local_develop_helper.py\", line 48, in _do_get\n    return super()._do_get(listener, name, timeout)\n  File \"/data/fmpc/wares/common/algo_data_transfer.py\", line 195, in _do_get\n    result, ename = listener.get_event_pickle_result(name, timeout)\n  File \"/data/fmpc/fmpc/base/EventListener.py\", line 29, in get_event_pickle_result\n    result_data, r_name = self.get_event_result(e_name, timeout)\n  File \"/data/fmpc/fmpc/utils/WrapUtils.py\", line 13, in wrap\n    result = func(*args, **kwargs)\n  File \"/data/fmpc/fmpc/base/EventListener.py\", line 165, in get_event_result\n    return_flag, r_data, e_name = self._handle_event_dt_from_transfer(event_dt, e_name)\n  File\"/data/fmpc/fmpc/base/EventListener.py\", line 91, in _handle_event_dt_from_transfer\n    raise RuntimeError(r_name, pickle.loads(r_data))\nRuntimeError: ('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\",line 377, in train\\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\\n  File \"fmpcbase/protocol/npz/npz.py\", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\\n  File \"fmpcbase/protocol/npz/npz.py\", line 498, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\\n  File \"fmpcbase/protocol/npz/npz.py\", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\\n  File \"fmpcbase/protocol/npz/npz.py\", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\\n  File \"fmpcbase/protocol/npz/npz.py\", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\\n  File \"fmpcbase/tensor/native.py\", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\\n  File \"/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 1175, in shape\\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 73, in do_start\\n    self.train()  # \u4f5c\u4e3a\u53d1\u8d77\u65b9\u8fdb\u884c\u6a21\u578b\u8bad\u7ec3\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 508, in train\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/fmpc/base/Algorithm.py\", line 103, in action\\n    self.start()\\n  File \"/data/fmpc/wares/common/base_algorithm.py\", line 337, in start\\n    self.do_start()\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 102, in do_start\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requestedshape requires a multiple of 32\\n'})\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 78, in do_start\n    self.train()  # \u4f5c\u4e3a\u53c2\u4e0e\u65b9\u8fdb\u884c\u6a21\u578b\u8bad\u7ec3\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 508, in train\n    raise RuntimeError('>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:{}'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 377, in train\\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\\n  File \"fmpcbase/protocol/npz/npz.py\", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\\n  File \"fmpcbase/protocol/npz/npz.py\", line 498, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\\n  File \"fmpcbase/protocol/npz/npz.py\", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\\n  File \"fmpcbase/protocol/npz/npz.py\", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\\n  File \"fmpcbase/protocol/npz/npz.py\", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\\n  File \"fmpcbase/tensor/native.py\", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\\n  File \"/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 1175, in shape\\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 73, in do_start\\n    self.train()  # \u4f5c\u4e3a\u53d1\u8d77\u65b9\u8fdb\u884c\u6a21\u578b\u8bad\u7ec3\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 508, in train\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/fmpc/base/Algorithm.py\", line 103, in action\\n    self.start()\\n  File \"/data/fmpc/wares/common/base_algorithm.py\", line 337, in start\\n    self.do_start()\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 102, in do_start\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n'})\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/data/fmpc/wares/common/base_ware.py\", line 71, in start\n    self.do_start(job, ctx, **kwargs)\n  File \"/data/fmpc/wares/common/base_ware.py\", line 123, in do_start\n    algo.action(job, ctx)\n  File \"/data/fmpc/fmpc/base/Algorithm.py\", line 105, in action\n    self.fin(e)\n  File \"/data/fmpc/wares/common/base_algorithm.py\", line 156, in fin\n    raise e\n  File \"/data/fmpc/fmpc/base/Algorithm.py\", line 103, in action\n    self.start()\n  File \"/data/fmpc/wares/common/base_algorithm.py\", line 337, in start\n    self.do_start()\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 102, in do_start\n    raise RuntimeError('>>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:{}'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 377, in train\\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\\n  File \"fmpcbase/protocol/npz/npz.py\", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\\n  File \"fmpcbase/protocol/npz/npz.py\", line 498, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\\n  File \"fmpcbase/protocol/npz/npz.py\", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\\n  File \"fmpcbase/protocol/npz/npz.py\", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\\n  File \"fmpcbase/protocol/npz/npz.py\", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\\n  File \"fmpcbase/tensor/native.py\", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\\n  File \"/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 1175, in shape\\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 73, in do_start\\n    self.train()  # \u4f5c\u4e3a\u53d1\u8d77\u65b9\u8fdb\u884c\u6a21\u578b\u8bad\u7ec3\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 508, in train\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/fmpc/base/Algorithm.py\", line 103, in action\\n    self.start()\\n  File \"/data/fmpc/wares/common/base_algorithm.py\", line 337, in start\\n    self.do_start()\\n File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 102, in do_start\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n'})\n", "time": 1688543632.1026833}
2023-07-05 15:53:52,106 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "error", "data": ">>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 377, in train\\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\\n  File \"fmpcbase/protocol/npz/npz.py\", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\\n  File \"fmpcbase/protocol/npz/npz.py\", line 498, infmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\\n  File \"fmpcbase/protocol/npz/npz.py\", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\\n  File \"fmpcbase/protocol/npz/npz.py\", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\\n  File \"fmpcbase/protocol/npz/npz.py\", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\\n  File \"fmpcbase/tensor/native.py\", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\\n  File \"/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 1175, in shape\\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 73, in do_start\\n    self.train()  # \u4f5c\u4e3a\u53d1\u8d77\u65b9\u8fdb\u884c\u6a21\u578b\u8bad\u7ec3\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 508, in train\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/fmpc/base/Algorithm.py\", line 103, in action\\n    self.start()\\n  File \"/data/fmpc/wares/common/base_algorithm.py\", line 337, in start\\n    self.do_start()\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 102, in do_start\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n'})", "time": 1688543632.0774338}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:52,113 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "error", "data": ">>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:Traceback (most recent call last):\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 444, in train\n    dw_shape_0, dw_shape_1, dw_remote_id = self.algo_data_transfer.op_dw_save.get(self.listener,\n  File \"/data/fmpc/wares/common/algo_data_transfer.py\", line 130, in get\n    ret = self._do_get(listener, full_name, timeout)\n  File \"/data/fmpc/wares/common/local_develop_helper.py\", line 48, in _do_get\n    return super()._do_get(listener, name, timeout)\n  File \"/data/fmpc/wares/common/algo_data_transfer.py\", line 195, in _do_get\n    result, ename = listener.get_event_pickle_result(name, timeout)\n  File \"/data/fmpc/fmpc/base/EventListener.py\", line 29,in get_event_pickle_result\n    result_data, r_name = self.get_event_result(e_name, timeout)\n  File \"/data/fmpc/fmpc/utils/WrapUtils.py\", line 13, in wrap\n    result = func(*args, **kwargs)\n  File \"/data/fmpc/fmpc/base/EventListener.py\", line 165, in get_event_result\n    return_flag, r_data, e_name =self._handle_event_dt_from_transfer(event_dt, e_name)\n  File \"/data/fmpc/fmpc/base/EventListener.py\", line 91, in _handle_event_dt_from_transfer\n    raise RuntimeError(r_name, pickle.loads(r_data))\nRuntimeError: ('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 377, in train\\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\\n  File \"fmpcbase/protocol/npz/npz.py\", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\\n  File \"fmpcbase/protocol/npz/npz.py\", line 498, infmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\\n  File \"fmpcbase/protocol/npz/npz.py\", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\\n  File \"fmpcbase/protocol/npz/npz.py\", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\\n  File \"fmpcbase/protocol/npz/npz.py\", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\\n  File \"fmpcbase/tensor/native.py\", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\\n  File \"/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 1175, in shape\\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 73, in do_start\\n    self.train()  # \u4f5c\u4e3a\u53d1\u8d77\u65b9\u8fdb\u884c\u6a21\u578b\u8bad\u7ec3\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 508, in train\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/fmpc/base/Algorithm.py\", line 103, in action\\n    self.start()\\n  File \"/data/fmpc/wares/common/base_algorithm.py\", line 337, in start\\n    self.do_start()\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 102, in do_start\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n'})\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 78, in do_start\n    self.train()  # \u4f5c\u4e3a\u53c2\u4e0e\u65b9\u8fdb\u884c\u6a21\u578b\u8bad\u7ec3\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 508, in train\n    raise RuntimeError('>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:{}'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 377, in train\\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\\n  File \"fmpcbase/protocol/npz/npz.py\", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\\n  File \"fmpcbase/protocol/npz/npz.py\", line 498, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\\n  File \"fmpcbase/protocol/npz/npz.py\", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\\n  File \"fmpcbase/protocol/npz/npz.py\", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\\n  File \"fmpcbase/protocol/npz/npz.py\", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\\n  File \"fmpcbase/tensor/native.py\", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\\n  File \"/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 1175, in shape\\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 73, in do_start\\n    self.train()  # \u4f5c\u4e3a\u53d1\u8d77\u65b9\u8fdb\u884c\u6a21\u578b\u8bad\u7ec3\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 508, in train\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/fmpc/base/Algorithm.py\", line 103, in action\\n    self.start()\\n  File \"/data/fmpc/wares/common/base_algorithm.py\", line 337, in start\\n    self.do_start()\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 102, in do_start\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n'})\n", "time": 1688543632.0813506}, response: {'code': '0', 'message':'OK', 'data': None, 'success': True}
2023-07-05 15:53:52,749 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "error", "data": ">>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 377, in train\\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\\n  File \"fmpcbase/protocol/npz/npz.py\", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\\n  File \"fmpcbase/protocol/npz/npz.py\", line 498, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\\n  File \"fmpcbase/protocol/npz/npz.py\", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\\n  File \"fmpcbase/protocol/npz/npz.py\", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\\n  File \"fmpcbase/protocol/npz/npz.py\", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\\n  File \"fmpcbase/tensor/native.py\", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\\n  File \"/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 1175, in shape\\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling ofthe above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 73, in do_start\\n    self.train()  # \u4f5c\u4e3a\u53d1\u8d77\u65b9\u8fdb\u884c\u6a21\u578b\u8bad\u7ec3\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 508, in train\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/fmpc/base/Algorithm.py\", line 103, in action\\n    self.start()\\n  File \"/data/fmpc/wares/common/base_algorithm.py\", line 337, in start\\n    self.do_start()\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 102, in do_start\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n'})", "time": 1688543632.0814168}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:53,128 - [MainProcess:49] EventHandler.py [Line:77] - WARNING - FW web not found job event，from cache: 1676499253109334017
2023-07-05 15:53:52,772 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "error", "data": "[InternalWareError] \u7ec4\u4ef6\u5185\u90e8\u9519\u8bef\u3002  cause: RuntimeError, >>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 377, in train\\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\\n  File \"fmpcbase/protocol/npz/npz.py\", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\\n  File \"fmpcbase/protocol/npz/npz.py\", line 498, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\\n  File \"fmpcbase/protocol/npz/npz.py\", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\\n  File \"fmpcbase/protocol/npz/npz.py\", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\\n  File \"fmpcbase/protocol/npz/npz.py\", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\\n  File \"fmpcbase/tensor/native.py\", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\\n  File \"/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 1175, in shape\\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 73, in do_start\\n    self.train()  # \u4f5c\u4e3a\u53d1\u8d77\u65b9\u8fdb\u884c\u6a21\u578b\u8bad\u7ec3\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 508, in train\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/fmpc/base/Algorithm.py\", line 103, in action\\n    self.start()\\n  File \"/data/fmpc/wares/common/base_algorithm.py\", line 337, in start\\n    self.do_start()\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 102, in do_start\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n'})", "time": 1688543632.102423}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:52,778 - [MpcPoolWorker-2:2:870] ReportLog.py [Line:40] - INFO - report log, param: {"jobId": "1676499580252463106", "level": "error", "data": "Traceback (most recent call last):\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 444, in train\n    dw_shape_0, dw_shape_1, dw_remote_id = self.algo_data_transfer.op_dw_save.get(self.listener,\n  File \"/data/fmpc/wares/common/algo_data_transfer.py\", line 130, in get\n    ret = self._do_get(listener, full_name, timeout)\n  File \"/data/fmpc/wares/common/local_develop_helper.py\", line 48, in _do_get\n    return super()._do_get(listener, name, timeout)\n  File \"/data/fmpc/wares/common/algo_data_transfer.py\", line 195, in _do_get\n    result, ename = listener.get_event_pickle_result(name, timeout)\n  File \"/data/fmpc/fmpc/base/EventListener.py\", line 29, in get_event_pickle_result\n    result_data, r_name = self.get_event_result(e_name, timeout)\n  File \"/data/fmpc/fmpc/utils/WrapUtils.py\", line 13, in wrap\n    result = func(*args, **kwargs)\n  File \"/data/fmpc/fmpc/base/EventListener.py\", line 165, in get_event_result\n    return_flag, r_data, e_name = self._handle_event_dt_from_transfer(event_dt, e_name)\n  File\"/data/fmpc/fmpc/base/EventListener.py\", line 91, in _handle_event_dt_from_transfer\n    raise RuntimeError(r_name, pickle.loads(r_data))\nRuntimeError: ('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\",line 377, in train\\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\\n  File \"fmpcbase/protocol/npz/npz.py\", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\\n  File \"fmpcbase/protocol/npz/npz.py\", line 498, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\\n  File \"fmpcbase/protocol/npz/npz.py\", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\\n  File \"fmpcbase/protocol/npz/npz.py\", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\\n  File \"fmpcbase/protocol/npz/npz.py\", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\\n  File \"fmpcbase/tensor/native.py\", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\\n  File \"/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 1175, in shape\\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 73, in do_start\\n    self.train()  # \u4f5c\u4e3a\u53d1\u8d77\u65b9\u8fdb\u884c\u6a21\u578b\u8bad\u7ec3\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 508, in train\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/fmpc/base/Algorithm.py\", line 103, in action\\n    self.start()\\n  File \"/data/fmpc/wares/common/base_algorithm.py\", line 337, in start\\n    self.do_start()\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 102, in do_start\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requestedshape requires a multiple of 32\\n'})\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 78, in do_start\n    self.train()  # \u4f5c\u4e3a\u53c2\u4e0e\u65b9\u8fdb\u884c\u6a21\u578b\u8bad\u7ec3\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 508, in train\n    raise RuntimeError('>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:{}'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 377, in train\\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\\n  File \"fmpcbase/protocol/npz/npz.py\", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\\n  File \"fmpcbase/protocol/npz/npz.py\", line 498, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\\n  File \"fmpcbase/protocol/npz/npz.py\", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\\n  File \"fmpcbase/protocol/npz/npz.py\", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\\n  File \"fmpcbase/protocol/npz/npz.py\", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\\n  File \"fmpcbase/tensor/native.py\", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\\n  File \"/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 1175, in shape\\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 73, in do_start\\n    self.train()  # \u4f5c\u4e3a\u53d1\u8d77\u65b9\u8fdb\u884c\u6a21\u578b\u8bad\u7ec3\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 508, in train\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/fmpc/base/Algorithm.py\", line 103, in action\\n    self.start()\\n  File \"/data/fmpc/wares/common/base_algorithm.py\", line 337, in start\\n    self.do_start()\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 102, in do_start\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n'})\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/data/fmpc/wares/common/base_ware.py\", line 71, in start\n    self.do_start(job, ctx, **kwargs)\n  File \"/data/fmpc/wares/common/base_ware.py\", line 123, in do_start\n    algo.action(job, ctx)\n  File \"/data/fmpc/fmpc/base/Algorithm.py\", line 105, in action\n    self.fin(e)\n  File \"/data/fmpc/wares/common/base_algorithm.py\", line 156, in fin\n    raise e\n  File \"/data/fmpc/fmpc/base/Algorithm.py\", line 103, in action\n    self.start()\n  File \"/data/fmpc/wares/common/base_algorithm.py\", line 337, in start\n    self.do_start()\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 102, in do_start\n    raise RuntimeError('>>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:{}'.format(ex))\nRuntimeError: >>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:('Job_Fin', {'type': 'FAIL', 'msg': 'Traceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 377, in train\\n    batch_op_y_error_bin_share = self.fmb.define_private_input(\\n  File \"fmpcbase/protocol/npz/npz.py\", line 640, in fmpcbase.protocol.npz.npz.NPZ.define_private_input\\n  File \"fmpcbase/protocol/npz/npz.py\", line 498, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 499, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 516, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation\\n  File \"fmpcbase/protocol/npz/npz.py\", line 472, in fmpcbase.protocol.npz.npz.NPZ.define_local_computation.share_output\\n  File \"fmpcbase/protocol/npz/npz.py\", line 783, in fmpcbase.protocol.npz.npz.NPZ._share_and_wrap\\n  File \"fmpcbase/protocol/npz/npz.py\", line 761, in fmpcbase.protocol.npz.npz.NPZ._share\\n  File \"fmpcbase/protocol/npz/npz.py\", line 764, in fmpcbase.protocol.npz.npz.NPZ._zero_share\\n  File \"fmpcbase/tensor/native.py\", line 606, in fmpcbase.tensor.native.native_factory.DenseTensor.shape\\n  File \"/usr/local/python3/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 1175, in shape\\n    self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())\\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 73, in do_start\\n    self.train()  # \u4f5c\u4e3a\u53d1\u8d77\u65b9\u8fdb\u884c\u6a21\u578b\u8bad\u7ec3\\n  File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 508, in train\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/data/fmpc/fmpc/base/Algorithm.py\", line 103, in action\\n    self.start()\\n  File \"/data/fmpc/wares/common/base_algorithm.py\", line 337, in start\\n    self.do_start()\\n File \"/data/fmpc/wares/hetero_lr_npz_hybrid_v2/lr_npz_hybrid_train_host.py\", line 102, in do_start\\n    raise RuntimeError(\\'>>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:{}\\'.format(ex))\\nRuntimeError: >>>> LR_NPZ_HYBRID \u4e3b\u4efb\u52a1\u6d41\u7a0b\u51fa\u9519:>>>> LR_NPZ_HYBRID \u6a21\u578b\u8bad\u7ec3\u5f02\u5e38:Input to reshape is a tensor with 3400 values, but the requested shape requires a multiple of 32\\n'})\n", "time": 1688543632.1026833}, response: {'code': '0', 'message': 'OK', 'data': None, 'success': True}
2023-07-05 15:53:53,295 - [MpcPoolWorker-2:2:870] ResourceInit.py [Line:152] - DEBUG - [process_exit_check]delete thread pool finish.....
2023-07-05 15:53:53,297 - [MpcPoolWorker-2:2:870] WareExecutor.py [Line:98] - INFO - FW job start [T3]_2：job=1676499580252463106, ware_info=cn.fudata.LR_NPZ_v2.1.0, ospid=870, time=1688543633.297652
2023-07-05 15:53:54,790 - [MpcPoolWorker-2:2:870] Process.py [Line:111] - DEBUG - worker start put job result...
2023-07-05 15:53:54,977 - [MpcPoolWorker-2:2:870] Process.py [Line:113] - DEBUG - worker start put job result finished...
2023-07-05 15:53:54,981 - [MainProcess:49] WareExecutor.py [Line:114] - INFO - FW  _end [T4]: job_id=1676499580252463106, ware_id=cn.fudata.LR_NPZ, time=1688543634.9816806
2023-07-05 15:53:54,983 - [MainProcess:49] EventsManager.py [Line:40] - INFO - release transf...
2023-07-05 15:53:54,983 - [MainProcess:49] EventsManager.py [Line:286] - DEBUG - FW: after del job event len(_Events_Dict): 0
2023-07-05 15:53:54,984 - [MainProcess:49] JobManager.py [Line:45] - DEBUG - [JobManager]remove job: 1676499580252463106:cn.fudata.LR_NPZ:2
2023-07-05 15:53:54,984 - [MainProcess:49] WareExecutor.py [Line:136] - INFO - FW  _end [T4]_2: job_id=1676499580252463106, ware_id=cn.fudata.LR_NPZ, time=1688543634.9846804
2023-07-05 15:53:54,993 - [MpcPoolWorker-2:2:870] Process.py [Line:125] - DEBUG - worker exiting after 1 tasks
2023-07-05 15:53:55,072 - [ForkProcess-2:865] Process.py [Line:274] - DEBUG - added worker
2023-07-05 15:53:55,191 - [MpcPoolWorker-2:34:1950] Process.py [Line:90] - DEBUG - worker start with thread count: 3
2023-07-05 15:53:56,128 - [MainProcess:49] EventHandler.py [Line:77] - WARNING - FW web not found job event，from cache: 1676499253109334017
2023-07-05 15:53:58,130 - [MainProcess:49] WaresM2anager.py [Line:78] - DEBUG - register ware, server name: 10.84.61.207:8000
2023-07-05 15:53:59,128 - [MainProcess:49] EventHandler.py [Line:77] - WARNING - FW web not found job event，from cache: 1676499253109334017
2023-07-05 15:54:02,128 - [MainProcess:49] EventHandler.py [Line:77] - WARNING - FW web not found job event，from cache: 1676499253109334017
2023-07-05 15:54:05,128 - [MainProcess:49] EventHandler.py [Line:77] - WARNING - FW web not found job event，from cache: 1676499253109334017
2023-07-05 15:54:08,128 - [MainProcess:49] EventHandler.py [Line:77] - WARNING - FW web not found job event，from cache: 1676499253109334017
2023-07-05 15:54:08,131 - [MainProcess:49] WaresManager.py [Line:78] - DEBUG - register ware, server name: 10.84.61.207:8000
2023-07-05 15:54:11,128 - [MainProcess:49] EventHandler.py [Line:77] - WARNING - FW web not found job event，from cache: 1676499253109334017
2023-07-05 15:54:14,128 - [MainProcess:49] EventHandler.py [Line:77] - WARNING - FW web not found job event，from cache: 1676499253109334017
2023-07-05 15:54:17,128 - [MainProcess:49] EventHandler.py [Line:77] - WARNING - FW web not found job event，from cache: 1676499253109334017
2023-07-05 15:54:18,130 - [MainProcess:49] WaresManager.py [Line:78] - DEBUG - register ware, server name: 10.84.61.207:8000
2023-07-05 15:54:20,128 - [MainProcess:49] EventHandler.py [Line:77] - WARNING - FW web not found job event，from cache: 1676499253109334017
2023-07-05 15:54:23,128 - [MainProcess:49] EventHandler.py [Line:77] - WARNING - FW web not found job event，from cache: 1676499253109334017
2023-07-05 15:54:26,128 - [MainProcess:49] EventHandler.py [Line:77] - WARNING - FW web not found job event，from cache: 1676499253109334017
2023-07-05 15:54:28,130 - [MainProcess:49] WaresManager.py [Line:78] - DEBUG - register ware, server name: 10.84.61.207:8000
2023-07-05 15:54:29,128 - [MainProcess:49] EventHandler.py [Line:77] - WARNING - FW web not found job event，from cache: 1676499253109334017
2023-07-05 15:54:32,128 - [MainProcess:49] EventHandler.py [Line:77] - WARNING - FW web not found job event，from cache: 1676499253109334017
2023-07-05 15:54:35,128 - [MainProcess:49] EventHandler.py [Line:77] - WARNING - FW web not found job event，from cache: 1676499253109334017
2023-07-05 15:54:38,128 - [MainProcess:49] EventHandler.py [Line:77] - WARNING - FW web not found job event，from cache: 1676499253109334017
2023-07-05 15:54:38,130 - [MainProcess:49] WaresManager.py [Line:78] - DEBUG - register ware, server name: 10.84.61.207:8000
2023-07-05 15:54:41,128 - [MainProcess:49] EventHandler.py [Line:77] - WARNING - FW web not found job event，from cache: 1676499253109334017
2023-07-05 15:54:48,131 - [MainProcess:49] WaresManager.py [Line:78] - DEBUG - register ware, server name: 10.84.61.207:8000
2023-07-05 15:54:58,131 - [MainProcess:49] WaresManager.py [Line:78] - DEBUG - register ware, server name: 10.84.61.207:8000
2023-07-05 15:55:08,130 - [MainProcess:49] WaresManager.py [Line:78] - DEBUG - register ware, server name: 10.84.61.207:8000
2023-07-05 15:55:18,134 - [MainProcess:49] WaresManager.py [Line:78] - DEBUG - register ware, server name: 10.84.61.207:8000
2023-07-05 15:55:28,131 - [MainProcess:49] WaresManager.py [Line:78] - DEBUG - register ware, server name: 10.84.61.207:8000
2023-07-05 15:55:38,130 - [MainProcess:49] WaresManager.py [Line:78] - DEBUG - register ware, server name: 10.84.61.207:8000
2023-07-05 15:55:48,132 - [MainProcess:49] WaresManager.py [Line:78] - DEBUG - register ware, server name: 10.84.61.207:8000
2023-07-05 15:55:58,130 - [MainProcess:49] WaresManager.py [Line:78] - DEBUG - register ware, server name: 10.84.61.207:8000
2023-07-05 15:56:08,130 - [MainProcess:49] WaresManager.py [Line:78] - DEBUG - register ware, server name: 10.84.61.207:8000
2023-07-05 15:56:18,130 - [MainProcess:49] WaresManager.py [Line:78] - DEBUG - register ware, server name: 10.84.61.207:8000
2023-07-05 15:56:28,130 - [MainProcess:49] WaresManager.py [Line:78] - DEBUG - register ware, server name: 10.84.61.207:8000
2023-07-05 15:56:38,131 - [MainProcess:49] WaresManager.py [Line:78] - DEBUG - register ware, server name: 10.84.61.207:8000
2023-07-05 15:56:48,130 - [MainProcess:49] WaresManager.py [Line:78] - DEBUG - register ware, server name: 10.84.61.207:8000
2023-07-05 15:56:58,130 - [MainProcess:49] WaresManager.py [Line:78] - DEBUG - register ware, server name: 10.84.61.207:8000
2023-07-05 15:57:08,129 - [MainProcess:49] WaresManager.py [Line:78] - DEBUG - register ware, server name: 10.84.61.207:8000
2023-07-05 15:57:18,130 - [MainProcess:49] WaresManager.py [Line:78] - DEBUG - register ware, server name: 10.84.61.207:8000
[root@avatar-fmpc-training-6cf98c79c6-4l6m8 logs]#